version: '3.3'

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data/

  redis:
    image: redis:alpine
    container_name: redis

  server:
    build:
      context: ../redmine_telegram_bot/.
      dockerfile: Dockerfile
    entrypoint: ./server-entrypoint.sh
    restart: always
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/usr/share/nginx/html/server/static/
      - media_value:/usr/share/nginx/html/server/media/
    depends_on:
      - redis
      - server

  celery:
    build:
      context: ../redmine_telegram_bot/.
      dockerfile: Dockerfile
    entrypoint: ./worker-entrypoint.sh
    restart: always
    volumes:
      - .:/app/celery

    depends_on:
      - redis
      - server
  celery-beat:
    build:
      context: ../redmine_telegram_bot/.
      dockerfile: Dockerfile
    entrypoint: ./beat-entrypoint.sh
    restart: always
    volumes:
      - .:/app/celery_beat
    depends_on:
      - redis
      - server
      - celery



volumes:
  postgres_db:
  static_value:
  media_value:
